### ISSUE TITLE
failed to convert coco to sequence file

### ISSUE THREAD

**Issue by kaiseu** [kaiseu/DLBenchmark#1]
[root@bb-node1 ssd]# java -cp /mnt/disk1/SSD_Predict/models/ssd/jars/object-detection-0.1-SNAPSHOT-jar-with-dependencies-and-spark.jar com.intel.analytics.zoo.pipeline.common.dataset.RoiImageSeqGenerator -f /mnt/disk1/SSD_Predict/data/COCO -o /mnt/disk1/SSD_Predict/data/COCO/seq/coco-minival -i coco_minival2014 -p 50
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at com.intel.analytics.zoo.pipeline.common.dataset.Coco$$anonfun$2.apply(Coco.scala:41)
        at com.intel.analytics.zoo.pipeline.common.dataset.Coco$$anonfun$2.apply(Coco.scala:38)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at scala.collection.AbstractIterator.to(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
        at com.intel.analytics.zoo.pipeline.common.dataset.Coco.getRoidb(Coco.scala:42)
        at com.intel.analytics.zoo.pipeline.common.dataset.RoiImageSeqGenerator$$anonfun$main$1.apply(RoiImageSeqGenerator.scala:65)
        at com.intel.analytics.zoo.pipeline.common.dataset.RoiImageSeqGenerator$$anonfun$main$1.apply(RoiImageSeqGenerator.scala:59)
        at scala.Option.map(Option.scala:146)
        at com.intel.analytics.zoo.pipeline.common.dataset.RoiImageSeqGenerator$.main(RoiImageSeqGenerator.scala:59)
        at com.intel.analytics.zoo.pipeline.common.dataset.RoiImageSeqGenerator.main(RoiImageSeqGenerator.scala)

**Comment by kaiseu** [comment]
Issue resolved.
